import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowLeft } from "lucide-react"

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 p-8 md:p-16 lg:p-24 selection:bg-indigo-500/30">
            <div className="max-w-3xl mx-auto space-y-8">
                <Link href="/login">
                    <Button variant="ghost" className="gap-2 mb-8 -ml-4 text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white">
                        <ArrowLeft className="w-4 h-4" /> Back to Login
                    </Button>
                </Link>

                <div className="space-y-4">
                    <h1 className="text-4xl font-serif font-black tracking-tight bg-gradient-to-r from-slate-900 to-slate-700 dark:from-white dark:to-slate-200 bg-clip-text text-transparent">
                        Terms of Service
                    </h1>
                    <p className="text-sm font-medium text-slate-500 dark:text-slate-400">Last updated: {new Date().toLocaleDateString()}</p>
                </div>

                <div className="prose prose-slate dark:prose-invert max-w-none space-y-6">
                    <p className="lead text-lg text-slate-600 dark:text-slate-300">
                        Welcome to EduGuide AI. Please read these Terms of Service carefully before using our platform.
                    </p>

                    <section className="space-y-4 pt-4 border-t border-slate-200 dark:border-slate-800">
                        <h2 className="text-2xl font-bold">1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using EduGuide AI, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.
                        </p>
                    </section>

                    <section className="space-y-4 pt-4 border-t border-slate-200 dark:border-slate-800">
                        <h2 className="text-2xl font-bold">2. Educational Content</h2>
                        <p>
                            The study materials, roadmaps, and flashcards generated by the AI are for educational purposes. We strive for accuracy but do not guarantee that all AI-generated content is perfectly accurate. It should be used as a supplementary learning tool.
                        </p>
                    </section>

                    <section className="space-y-4 pt-4 border-t border-slate-200 dark:border-slate-800">
                        <h2 className="text-2xl font-bold">3. User Accounts</h2>
                        <p>
                            You are responsible for safeguarding the password that you use to access the service and for any activities or actions under your password.
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>You must provide accurate, complete, and current registration information.</li>
                            <li>You may not use as a username the name of another person or entity.</li>
                        </ul>
                    </section>

                    <section className="space-y-4 pt-4 border-t border-slate-200 dark:border-slate-800">
                        <h2 className="text-2xl font-bold">4. Acceptable Use</h2>
                        <p>
                            You agree not to use the service to generate content that is illegal, abusive, harassing, or otherwise violating the rights of others.
                            Automated scraping or abusive API requests to our AI endpoints will result in immediate account termination.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    )
}
